### ISSUE TITLE
can't see text with highlight in vim-mode

### ISSUE THREAD

**Issue by alok** [roam-unofficial/roam-toolkit#143]
it's very hard to make out the cursor or the text underneath the bright yellow highlight. is there a way to make it light grey or something?

<img width="874" alt="Screenshot 2020-07-23 at 12 09 53 PM" src="https://user-images.githubusercontent.com/8325708/88328577-84701c80-ccdd-11ea-8ac2-17cfe0e7bc78.png">

**Comment by tntmarket** [comment]
Hey, you can add a custom css style targeting

```css
.roam-toolkit-block-mode--highlight {
    background-color: black;
}
```
