### ISSUE TITLE
Vim navigation highlight defaults to yellow

### ISSUE THREAD

**Issue by CLocs** [roam-unofficial/roam-toolkit#183]
Vim navigation rocks. Thank you so much! You nailed it. 

Unfortunately, the highlight for vim navigation is almost always yellow in all [RoamThemes](https://chrome.google.com/webstore/detail/roamthemes/iinnlcahmailoholehlbhbefddpbojpa?hl=en), making dark themes useless: white text over yellow highlight. 

Question/Request: can Roam Toolkit override the highlight color in RoamThemes? 
![image](https://user-images.githubusercontent.com/4088633/100419308-28c1f100-3039-11eb-9685-815cf662f308.png)

**Comment by RobertKirk** [comment]
You can adjust this yourself using `[[roam/css]]`, for example I use:

```css
.roam-toolkit-block-mode--highlight {
  background-image: linear-gradient(to right, rgba(var(--sol-cyan-rgb), 0.3), transparent);
  border-radius: 5px;
  background-color: unset !important;
}
```
